# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/system_pin.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_OVSensor_0_0/system_OVSensor_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_OVSensor_0_0 || ORIG_REF_NAME==system_OVSensor_0_0} -quiet] -quiet

# IP: bd/system/ip/system_OVSensor_1_0/system_OVSensor_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_OVSensor_1_0 || ORIG_REF_NAME==system_OVSensor_1_0} -quiet] -quiet

# IP: bd/system/ip/system_HDMI_tx_0_0/system_HDMI_tx_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_HDMI_tx_0_0 || ORIG_REF_NAME==system_HDMI_tx_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_vdma_0_0 || ORIG_REF_NAME==system_axi_vdma_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_vdma_1_0/system_axi_vdma_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_vdma_1_0 || ORIG_REF_NAME==system_axi_vdma_1_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_vdma_2_0/system_axi_vdma_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_vdma_2_0 || ORIG_REF_NAME==system_axi_vdma_2_0} -quiet] -quiet

# IP: bd/system/ip/system_v_vid_in_axi4s_0_0/system_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==system_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: bd/system/ip/system_v_vid_in_axi4s_1_0/system_v_vid_in_axi4s_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_vid_in_axi4s_1_0 || ORIG_REF_NAME==system_v_vid_in_axi4s_1_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_vdma_0_1/system_axi_vdma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_vdma_0_1 || ORIG_REF_NAME==system_axi_vdma_0_1} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_0_0 || ORIG_REF_NAME==system_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] -quiet

# IP: bd/system/ip/system_util_vector_logic_0_0/system_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_vector_logic_0_0 || ORIG_REF_NAME==system_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/system/ip/system_v_tc_0_0/system_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_tc_0_0 || ORIG_REF_NAME==system_v_tc_0_0} -quiet] -quiet

# IP: bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==system_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_0/system_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_0 || ORIG_REF_NAME==system_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_1/system_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_1 || ORIG_REF_NAME==system_xbar_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_1_0/system_axi_interconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_interconnect_1_0 || ORIG_REF_NAME==system_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_2/system_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_2 || ORIG_REF_NAME==system_xbar_2} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_2_0/system_axi_interconnect_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_interconnect_2_0 || ORIG_REF_NAME==system_axi_interconnect_2_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconcat_0_0/system_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconcat_0_0 || ORIG_REF_NAME==system_xlconcat_0_0} -quiet] -quiet

# IP: bd/system/ip/system_v_mix_0_0/system_v_mix_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_mix_0_0 || ORIG_REF_NAME==system_v_mix_0_0} -quiet] -quiet

# IP: bd/system/ip/system_ila_0_0/system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ila_0_0 || ORIG_REF_NAME==system_ila_0_0} -quiet] -quiet

# IP: bd/system/ip/system_ila_1_0/system_ila_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ila_1_0 || ORIG_REF_NAME==system_ila_1_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/system_system_ila_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_system_ila_0_1 || ORIG_REF_NAME==system_system_ila_0_1} -quiet] -quiet

# Block Designs: bd/system/ip/system_system_ila_0_1/bd_0/bd_1579.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579 || ORIG_REF_NAME==bd_1579} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_0/bd_1579_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_ila_lib_0 || ORIG_REF_NAME==bd_1579_ila_lib_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_1/bd_1579_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_g_inst_0 || ORIG_REF_NAME==bd_1579_g_inst_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_2/bd_1579_slot_0_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_0_aw_0 || ORIG_REF_NAME==bd_1579_slot_0_aw_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_3/bd_1579_slot_0_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_0_w_0 || ORIG_REF_NAME==bd_1579_slot_0_w_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_4/bd_1579_slot_0_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_0_b_0 || ORIG_REF_NAME==bd_1579_slot_0_b_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_5/bd_1579_slot_0_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_0_ar_0 || ORIG_REF_NAME==bd_1579_slot_0_ar_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_6/bd_1579_slot_0_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_0_r_0 || ORIG_REF_NAME==bd_1579_slot_0_r_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_7/bd_1579_slot_1_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_1_aw_0 || ORIG_REF_NAME==bd_1579_slot_1_aw_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_8/bd_1579_slot_1_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_1_w_0 || ORIG_REF_NAME==bd_1579_slot_1_w_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_9/bd_1579_slot_1_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_1_b_0 || ORIG_REF_NAME==bd_1579_slot_1_b_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_10/bd_1579_slot_1_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_1_ar_0 || ORIG_REF_NAME==bd_1579_slot_1_ar_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_11/bd_1579_slot_1_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_1_r_0 || ORIG_REF_NAME==bd_1579_slot_1_r_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_12/bd_1579_slot_3_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_3_aw_0 || ORIG_REF_NAME==bd_1579_slot_3_aw_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_13/bd_1579_slot_3_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_3_w_0 || ORIG_REF_NAME==bd_1579_slot_3_w_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_14/bd_1579_slot_3_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_3_b_0 || ORIG_REF_NAME==bd_1579_slot_3_b_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_15/bd_1579_slot_3_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_3_ar_0 || ORIG_REF_NAME==bd_1579_slot_3_ar_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_16/bd_1579_slot_3_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_3_r_0 || ORIG_REF_NAME==bd_1579_slot_3_r_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_17/bd_1579_slot_5_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_5_aw_0 || ORIG_REF_NAME==bd_1579_slot_5_aw_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_18/bd_1579_slot_5_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_5_w_0 || ORIG_REF_NAME==bd_1579_slot_5_w_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_19/bd_1579_slot_5_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_5_b_0 || ORIG_REF_NAME==bd_1579_slot_5_b_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_20/bd_1579_slot_5_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_5_ar_0 || ORIG_REF_NAME==bd_1579_slot_5_ar_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_21/bd_1579_slot_5_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_5_r_0 || ORIG_REF_NAME==bd_1579_slot_5_r_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_22/bd_1579_slot_6_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_6_aw_0 || ORIG_REF_NAME==bd_1579_slot_6_aw_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_23/bd_1579_slot_6_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_6_w_0 || ORIG_REF_NAME==bd_1579_slot_6_w_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_24/bd_1579_slot_6_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_6_b_0 || ORIG_REF_NAME==bd_1579_slot_6_b_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_25/bd_1579_slot_6_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_6_ar_0 || ORIG_REF_NAME==bd_1579_slot_6_ar_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_26/bd_1579_slot_6_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_6_r_0 || ORIG_REF_NAME==bd_1579_slot_6_r_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_27/bd_1579_slot_7_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_7_aw_0 || ORIG_REF_NAME==bd_1579_slot_7_aw_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_28/bd_1579_slot_7_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_7_w_0 || ORIG_REF_NAME==bd_1579_slot_7_w_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_29/bd_1579_slot_7_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_7_b_0 || ORIG_REF_NAME==bd_1579_slot_7_b_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_30/bd_1579_slot_7_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_7_ar_0 || ORIG_REF_NAME==bd_1579_slot_7_ar_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_31/bd_1579_slot_7_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_7_r_0 || ORIG_REF_NAME==bd_1579_slot_7_r_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_1_1/system_system_ila_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_system_ila_1_1 || ORIG_REF_NAME==system_system_ila_1_1} -quiet] -quiet

# Block Designs: bd/system/ip/system_system_ila_1_1/bd_0/bd_d528.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d528 || ORIG_REF_NAME==bd_d528} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_1_1/bd_0/ip/ip_0/bd_d528_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d528_ila_lib_0 || ORIG_REF_NAME==bd_d528_ila_lib_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_2_1/system_system_ila_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_system_ila_2_1 || ORIG_REF_NAME==system_system_ila_2_1} -quiet] -quiet

# Block Designs: bd/system/ip/system_system_ila_2_1/bd_0/bd_d5d8.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d5d8 || ORIG_REF_NAME==bd_d5d8} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_2_1/bd_0/ip/ip_0/bd_d5d8_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d5d8_ila_lib_0 || ORIG_REF_NAME==bd_d5d8_ila_lib_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_7_2/system_system_ila_7_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_system_ila_7_2 || ORIG_REF_NAME==system_system_ila_7_2} -quiet] -quiet

# Block Designs: bd/system/ip/system_system_ila_7_2/bd_0/bd_d588.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d588 || ORIG_REF_NAME==bd_d588} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_7_2/bd_0/ip/ip_0/bd_d588_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d588_ila_lib_0 || ORIG_REF_NAME==bd_d588_ila_lib_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_4_3/system_system_ila_4_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_system_ila_4_3 || ORIG_REF_NAME==system_system_ila_4_3} -quiet] -quiet

# Block Designs: bd/system/ip/system_system_ila_4_3/bd_0/bd_15b9.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_15b9 || ORIG_REF_NAME==bd_15b9} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_4_3/bd_0/ip/ip_0/bd_15b9_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_15b9_ila_lib_0 || ORIG_REF_NAME==bd_15b9_ila_lib_0} -quiet] -quiet

# IP: bd/system/ip/system_util_vector_logic_1_0/system_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_vector_logic_1_0 || ORIG_REF_NAME==system_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_1/system_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_1 || ORIG_REF_NAME==system_auto_pc_1} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_2/system_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_2 || ORIG_REF_NAME==system_auto_pc_2} -quiet] -quiet

# XDC: bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_vdma_0_0 || ORIG_REF_NAME==system_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_vdma_0_0 || ORIG_REF_NAME==system_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0_ooc.xdc

# XDC: bd/system/ip/system_axi_vdma_1_0/system_axi_vdma_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_vdma_1_0 || ORIG_REF_NAME==system_axi_vdma_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_vdma_1_0/system_axi_vdma_1_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_vdma_1_0 || ORIG_REF_NAME==system_axi_vdma_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_vdma_1_0/system_axi_vdma_1_0_ooc.xdc

# XDC: bd/system/ip/system_axi_vdma_2_0/system_axi_vdma_2_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_vdma_2_0 || ORIG_REF_NAME==system_axi_vdma_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_vdma_2_0/system_axi_vdma_2_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_vdma_2_0 || ORIG_REF_NAME==system_axi_vdma_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_vdma_2_0/system_axi_vdma_2_0_ooc.xdc

# XDC: bd/system/ip/system_v_vid_in_axi4s_0_0/system_v_vid_in_axi4s_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==system_v_vid_in_axi4s_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_v_vid_in_axi4s_1_0/system_v_vid_in_axi4s_1_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_v_vid_in_axi4s_1_0 || ORIG_REF_NAME==system_v_vid_in_axi4s_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_vdma_0_1/system_axi_vdma_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_vdma_0_1 || ORIG_REF_NAME==system_axi_vdma_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_vdma_0_1/system_axi_vdma_0_1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_vdma_0_1 || ORIG_REF_NAME==system_axi_vdma_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_vdma_0_1/system_axi_vdma_0_1_ooc.xdc

# XDC: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_0_0 || ORIG_REF_NAME==system_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_0_0 || ORIG_REF_NAME==system_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_ooc.xdc

# XDC: bd/system/ip/system_v_tc_0_0/system_v_tc_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_v_tc_0_0 || ORIG_REF_NAME==system_v_tc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==system_v_axi4s_vid_out_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_v_mix_0_0/system_v_mix_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_v_mix_0_0 || ORIG_REF_NAME==system_v_mix_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_ila_0_0 || ORIG_REF_NAME==system_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_ila_0_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_ila_0_0 || ORIG_REF_NAME==system_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_ila_0_0/system_ila_0_0_ooc.xdc

# XDC: bd/system/ip/system_ila_1_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_ila_1_0 || ORIG_REF_NAME==system_ila_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_ila_1_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_ila_1_0 || ORIG_REF_NAME==system_ila_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_ila_1_0/system_ila_1_0_ooc.xdc

# XDC: bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1579_ila_lib_0 || ORIG_REF_NAME==bd_1579_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1579_ila_lib_0 || ORIG_REF_NAME==bd_1579_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_0/bd_1579_ila_lib_0_ooc.xdc

# XDC: bd/system/ip/system_system_ila_0_1/bd_0/bd_1579_ooc.xdc

# XDC: bd/system/ip/system_system_ila_1_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d528_ila_lib_0 || ORIG_REF_NAME==bd_d528_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_system_ila_1_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d528_ila_lib_0 || ORIG_REF_NAME==bd_d528_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_system_ila_1_1/bd_0/ip/ip_0/bd_d528_ila_lib_0_ooc.xdc

# XDC: bd/system/ip/system_system_ila_1_1/bd_0/bd_d528_ooc.xdc

# XDC: bd/system/ip/system_system_ila_2_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d5d8_ila_lib_0 || ORIG_REF_NAME==bd_d5d8_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_system_ila_2_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d5d8_ila_lib_0 || ORIG_REF_NAME==bd_d5d8_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_system_ila_2_1/bd_0/ip/ip_0/bd_d5d8_ila_lib_0_ooc.xdc

# XDC: bd/system/ip/system_system_ila_2_1/bd_0/bd_d5d8_ooc.xdc

# XDC: bd/system/ip/system_system_ila_7_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d588_ila_lib_0 || ORIG_REF_NAME==bd_d588_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_system_ila_7_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d588_ila_lib_0 || ORIG_REF_NAME==bd_d588_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_system_ila_7_2/bd_0/ip/ip_0/bd_d588_ila_lib_0_ooc.xdc

# XDC: bd/system/ip/system_system_ila_7_2/bd_0/bd_d588_ooc.xdc

# XDC: bd/system/ip/system_system_ila_4_3/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_15b9_ila_lib_0 || ORIG_REF_NAME==bd_15b9_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_system_ila_4_3/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_15b9_ila_lib_0 || ORIG_REF_NAME==bd_15b9_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_system_ila_4_3/bd_0/ip/ip_0/bd_15b9_ila_lib_0_ooc.xdc

# XDC: bd/system/ip/system_system_ila_4_3/bd_0/bd_15b9_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_2/system_auto_pc_2_ooc.xdc

# XDC: bd/system/system_ooc.xdc
