# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/ila_m0/ila_m0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_m0 || ORIG_REF_NAME==ila_m0} -quiet] -quiet

# IP: ip/fifo_ip/fifo_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_ip || ORIG_REF_NAME==fifo_ip} -quiet] -quiet

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: ip/ila_m0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_m0 || ORIG_REF_NAME==ila_m0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/ila_m0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_m0 || ORIG_REF_NAME==ila_m0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/ila_m0/ila_m0_ooc.xdc

# XDC: ip/fifo_ip/fifo_ip.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_ip || ORIG_REF_NAME==fifo_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/fifo_ip/fifo_ip_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_ip || ORIG_REF_NAME==fifo_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/clk_wiz_0/clk_wiz_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clk_wiz_0/clk_wiz_0_ooc.xdc
