# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_sys/Miz_sys.cache/wt [current_project]
set_property parent.project_path F:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_sys/Miz_sys.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  f:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_ip_lib/AXI_OLED
  f:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_ip_lib/HDMI_FPGA_ML
  f:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_ip_lib/OV_Sensor_ML
} [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files F:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_sys/Miz_sys.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all f:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_50M_0/system_rst_processing_system7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_50M_0/system_rst_processing_system7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all f:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_50M_0/system_rst_processing_system7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_v_vid_in_axi4s_0_0/system_v_vid_in_axi4s_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_v_vid_in_axi4s_0_0/system_v_vid_in_axi4s_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_v_tc_0_0/system_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_v_tc_0_0/system_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_xbar_1/system_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_auto_us_0/system_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_auto_us_0/system_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_auto_us_1/system_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_auto_us_1/system_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all F:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_sys/Miz_sys.srcs/sources_1/bd/system/system_ooc.xdc]
set_property is_locked true [get_files F:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_sys/Miz_sys.srcs/sources_1/bd/system/system.bd]

read_verilog -library xil_defaultlib F:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_sys/Miz_sys.srcs/sources_1/system_wrapper_dma.v
read_xdc F:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_sys/Miz_sys.srcs/constrs_1/new/Miz_sys_pin.xdc
set_property used_in_implementation false [get_files F:/miz701N/7020/s3/S03-CH04_AXI_DMA_OV5640_HDMI/Miz_sys/Miz_sys.srcs/constrs_1/new/Miz_sys_pin.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top system_wrapper -part xc7z020clg400-2
write_checkpoint -noxdef system_wrapper.dcp
catch { report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb }
