# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/system_pin.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_OVSensor_0_0/system_OVSensor_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_OVSensor_0_0 || ORIG_REF_NAME==system_OVSensor_0_0} -quiet] -quiet

# IP: bd/system/ip/system_v_vid_in_axi4s_0_0/system_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==system_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_0_0 || ORIG_REF_NAME==system_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_vdma_0_0 || ORIG_REF_NAME==system_axi_vdma_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_0/system_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_0 || ORIG_REF_NAME==system_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_2_0/system_axi_interconnect_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_interconnect_2_0 || ORIG_REF_NAME==system_axi_interconnect_2_0} -quiet] -quiet

# IP: bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==system_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/system/ip/system_HDMI_tx_0_0/system_HDMI_tx_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_HDMI_tx_0_0 || ORIG_REF_NAME==system_HDMI_tx_0_0} -quiet] -quiet

# IP: bd/system/ip/system_v_tc_0_0/system_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_tc_0_0 || ORIG_REF_NAME==system_v_tc_0_0} -quiet] -quiet

# IP: bd/system/ip/system_util_vector_logic_0_0/system_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_vector_logic_0_0 || ORIG_REF_NAME==system_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_0_0/system_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0_0 || ORIG_REF_NAME==system_xlconstant_0_0} -quiet] -quiet

# IP: bd/system/ip/system_util_vector_logic_1_0/system_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_vector_logic_1_0 || ORIG_REF_NAME==system_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_0/system_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_system_ila_0_0 || ORIG_REF_NAME==system_system_ila_0_0} -quiet] -quiet

# Block Designs: bd/system/ip/system_system_ila_0_0/bd_0/bd_d5b8.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d5b8 || ORIG_REF_NAME==bd_d5b8} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_0/bd_d5b8_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d5b8_ila_lib_0 || ORIG_REF_NAME==bd_d5b8_ila_lib_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_1/bd_d5b8_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d5b8_g_inst_0 || ORIG_REF_NAME==bd_d5b8_g_inst_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_1_0/system_system_ila_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_system_ila_1_0 || ORIG_REF_NAME==system_system_ila_1_0} -quiet] -quiet

# Block Designs: bd/system/ip/system_system_ila_1_0/bd_0/bd_15e9.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_15e9 || ORIG_REF_NAME==bd_15e9} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_1_0/bd_0/ip/ip_0/bd_15e9_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_15e9_ila_lib_0 || ORIG_REF_NAME==bd_15e9_ila_lib_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_2_0/system_system_ila_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_system_ila_2_0 || ORIG_REF_NAME==system_system_ila_2_0} -quiet] -quiet

# Block Designs: bd/system/ip/system_system_ila_2_0/bd_0/bd_1519.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1519 || ORIG_REF_NAME==bd_1519} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_2_0/bd_0/ip/ip_0/bd_1519_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1519_ila_lib_0 || ORIG_REF_NAME==bd_1519_ila_lib_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_3_0/system_system_ila_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_system_ila_3_0 || ORIG_REF_NAME==system_system_ila_3_0} -quiet] -quiet

# Block Designs: bd/system/ip/system_system_ila_3_0/bd_0/bd_d548.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d548 || ORIG_REF_NAME==bd_d548} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_3_0/bd_0/ip/ip_0/bd_d548_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d548_ila_lib_0 || ORIG_REF_NAME==bd_d548_ila_lib_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_4_0/system_system_ila_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_system_ila_4_0 || ORIG_REF_NAME==system_system_ila_4_0} -quiet] -quiet

# Block Designs: bd/system/ip/system_system_ila_4_0/bd_0/bd_14f9.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_14f9 || ORIG_REF_NAME==bd_14f9} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_4_0/bd_0/ip/ip_0/bd_14f9_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_14f9_ila_lib_0 || ORIG_REF_NAME==bd_14f9_ila_lib_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_1/system_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_1 || ORIG_REF_NAME==system_auto_pc_1} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_5_0/system_system_ila_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_system_ila_5_0 || ORIG_REF_NAME==system_system_ila_5_0} -quiet] -quiet

# Block Designs: bd/system/ip/system_system_ila_5_0/bd_0/bd_d4a8.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d4a8 || ORIG_REF_NAME==bd_d4a8} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_5_0/bd_0/ip/ip_0/bd_d4a8_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d4a8_ila_lib_0 || ORIG_REF_NAME==bd_d4a8_ila_lib_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_6_1/system_system_ila_6_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_system_ila_6_1 || ORIG_REF_NAME==system_system_ila_6_1} -quiet] -quiet

# Block Designs: bd/system/ip/system_system_ila_6_1/bd_0/bd_1499.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1499 || ORIG_REF_NAME==bd_1499} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_6_1/bd_0/ip/ip_0/bd_1499_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1499_ila_lib_0 || ORIG_REF_NAME==bd_1499_ila_lib_0} -quiet] -quiet

# XDC: bd/system/ip/system_v_vid_in_axi4s_0_0/system_v_vid_in_axi4s_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==system_v_vid_in_axi4s_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_0_0 || ORIG_REF_NAME==system_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_0_0 || ORIG_REF_NAME==system_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_ooc.xdc

# XDC: bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_vdma_0_0 || ORIG_REF_NAME==system_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_vdma_0_0 || ORIG_REF_NAME==system_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0_ooc.xdc

# XDC: bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==system_v_axi4s_vid_out_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_v_tc_0_0/system_v_tc_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_v_tc_0_0 || ORIG_REF_NAME==system_v_tc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d5b8_ila_lib_0 || ORIG_REF_NAME==bd_d5b8_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d5b8_ila_lib_0 || ORIG_REF_NAME==bd_d5b8_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_0/bd_d5b8_ila_lib_0_ooc.xdc

# XDC: bd/system/ip/system_system_ila_0_0/bd_0/bd_d5b8_ooc.xdc

# XDC: bd/system/ip/system_system_ila_0_0/system_system_ila_0_0_ooc.xdc

# XDC: bd/system/ip/system_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_15e9_ila_lib_0 || ORIG_REF_NAME==bd_15e9_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_15e9_ila_lib_0 || ORIG_REF_NAME==bd_15e9_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_system_ila_1_0/bd_0/ip/ip_0/bd_15e9_ila_lib_0_ooc.xdc

# XDC: bd/system/ip/system_system_ila_1_0/bd_0/bd_15e9_ooc.xdc

# XDC: bd/system/ip/system_system_ila_1_0/system_system_ila_1_0_ooc.xdc

# XDC: bd/system/ip/system_system_ila_2_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1519_ila_lib_0 || ORIG_REF_NAME==bd_1519_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_system_ila_2_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1519_ila_lib_0 || ORIG_REF_NAME==bd_1519_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_system_ila_2_0/bd_0/ip/ip_0/bd_1519_ila_lib_0_ooc.xdc

# XDC: bd/system/ip/system_system_ila_2_0/bd_0/bd_1519_ooc.xdc

# XDC: bd/system/ip/system_system_ila_2_0/system_system_ila_2_0_ooc.xdc

# XDC: bd/system/ip/system_system_ila_3_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d548_ila_lib_0 || ORIG_REF_NAME==bd_d548_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_system_ila_3_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d548_ila_lib_0 || ORIG_REF_NAME==bd_d548_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_system_ila_3_0/bd_0/ip/ip_0/bd_d548_ila_lib_0_ooc.xdc

# XDC: bd/system/ip/system_system_ila_3_0/bd_0/bd_d548_ooc.xdc

# XDC: bd/system/ip/system_system_ila_3_0/system_system_ila_3_0_ooc.xdc

# XDC: bd/system/ip/system_system_ila_4_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_14f9_ila_lib_0 || ORIG_REF_NAME==bd_14f9_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_system_ila_4_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_14f9_ila_lib_0 || ORIG_REF_NAME==bd_14f9_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_system_ila_4_0/bd_0/ip/ip_0/bd_14f9_ila_lib_0_ooc.xdc

# XDC: bd/system/ip/system_system_ila_4_0/bd_0/bd_14f9_ooc.xdc

# XDC: bd/system/ip/system_system_ila_4_0/system_system_ila_4_0_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc

# XDC: bd/system/ip/system_system_ila_5_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d4a8_ila_lib_0 || ORIG_REF_NAME==bd_d4a8_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_system_ila_5_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d4a8_ila_lib_0 || ORIG_REF_NAME==bd_d4a8_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_system_ila_5_0/bd_0/ip/ip_0/bd_d4a8_ila_lib_0_ooc.xdc

# XDC: bd/system/ip/system_system_ila_5_0/bd_0/bd_d4a8_ooc.xdc

# XDC: bd/system/ip/system_system_ila_5_0/system_system_ila_5_0_ooc.xdc

# XDC: bd/system/ip/system_system_ila_6_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1499_ila_lib_0 || ORIG_REF_NAME==bd_1499_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_system_ila_6_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1499_ila_lib_0 || ORIG_REF_NAME==bd_1499_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_system_ila_6_1/bd_0/ip/ip_0/bd_1499_ila_lib_0_ooc.xdc

# XDC: bd/system/ip/system_system_ila_6_1/bd_0/bd_1499_ooc.xdc

# XDC: bd/system/ip/system_system_ila_6_1/system_system_ila_6_1_ooc.xdc

# XDC: bd/system/system_ooc.xdc
