webtalk_init -webtalk_dir E:\\Project\\Personal\\PoseEstimation\\SourceCode\\ZYNQ\\course_s2_sdk\\25_ov5640_sd\\ov5640_sd.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-10-06 14:14:42" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "nun08ul7aemhdu3f4gjp1bqrq6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_13" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "13" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4200H CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2794 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.057 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1601950410861" -context "sdk\\\\hardware/1601950410861"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1601950410861"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1601950410861"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1601950410861"
webtalk_add_data -client sdk -key VivadoVersion -value "2017.4" -context "sdk\\\\hardware/1601950410861"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1601950410861"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1601950410861"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1601950410861"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1601950410861"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1601950410861"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1601950410861"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1601964882878"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1601964882878"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1601964882878"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1601964882878"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1601964882878"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1601964882878"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1601964882878"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1601964882878"
webtalk_transmit -clientid 1908046083 -regid "" -xml E:\\Project\\Personal\\PoseEstimation\\SourceCode\\ZYNQ\\course_s2_sdk\\25_ov5640_sd\\ov5640_sd.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html E:\\Project\\Personal\\PoseEstimation\\SourceCode\\ZYNQ\\course_s2_sdk\\25_ov5640_sd\\ov5640_sd.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm E:\\Project\\Personal\\PoseEstimation\\SourceCode\\ZYNQ\\course_s2_sdk\\25_ov5640_sd\\ov5640_sd.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
