webtalk_init -webtalk_dir E:\\Project\\Personal\\StereoVision\\Project_FPGA\\StereoDisplay\\system\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-03-21 13:56:49" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vitis v2019.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "Vitis" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "i0j4sh9q5mjhn8f7sr9snt1nnt" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.2_4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4200H CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2794 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.856 GB" -context "user_environment"
webtalk_register_client -client vitis
webtalk_add_data -client vitis -key uid -value "1584688156958" -context "vitis\\\\platform/1584688156958"
webtalk_add_data -client vitis -key platform_source -value "dsa" -context "vitis\\\\platform/1584688156958"
webtalk_add_data -client vitis -key os -value "standalone" -context "vitis\\\\platform/1584688156958"
webtalk_add_data -client vitis -key processor -value "ps7_cortexa9" -context "vitis\\\\platform/1584688156958"
webtalk_add_data -client vitis -key platform -value "NA" -context "vitis\\\\platform/1584688156958"
webtalk_add_data -client vitis -key uid -value "1584688330931" -context "vitis\\\\application/1584688330931"
webtalk_add_data -client vitis -key project_type -value "sdk" -context "vitis\\\\application/1584688330931"
webtalk_add_data -client vitis -key os -value "standalone" -context "vitis\\\\application/1584688330931"
webtalk_add_data -client vitis -key processor -value "cortex-a9" -context "vitis\\\\application/1584688330931"
webtalk_add_data -client vitis -key runtime -value "C/C++" -context "vitis\\\\application/1584688330931"
webtalk_add_data -client vitis -key template -value "empty" -context "vitis\\\\application/1584688330931"
webtalk_add_data -client vitis -key platform -value "custom" -context "vitis\\\\application/1584688330931"
webtalk_add_data -client vitis -key platform_type -value "fixed" -context "vitis\\\\application/1584688330931"
webtalk_add_data -client vitis -key application_type -value "application" -context "vitis\\\\application/1584688330931"
webtalk_add_data -client vitis -key platform_source -value "platform" -context "vitis\\\\application/1584688330931"
webtalk_add_data -client vitis -key device_family -value "zynq" -context "vitis\\\\application/1584688330931"
webtalk_add_data -client vitis -key fpga -value "xc7z020" -context "vitis\\\\application/1584688330931"
webtalk_add_data -client vitis -key uid -value "1584701094404" -context "vitis\\\\application/1584701094404"
webtalk_add_data -client vitis -key project_type -value "sdk" -context "vitis\\\\application/1584701094404"
webtalk_add_data -client vitis -key os -value "standalone" -context "vitis\\\\application/1584701094404"
webtalk_add_data -client vitis -key processor -value "cortex-a9" -context "vitis\\\\application/1584701094404"
webtalk_add_data -client vitis -key runtime -value "C/C++" -context "vitis\\\\application/1584701094404"
webtalk_add_data -client vitis -key template -value "sdk" -context "vitis\\\\application/1584701094404"
webtalk_add_data -client vitis -key platform -value "custom" -context "vitis\\\\application/1584701094404"
webtalk_add_data -client vitis -key platform_type -value "fixed" -context "vitis\\\\application/1584701094404"
webtalk_add_data -client vitis -key application_type -value "application" -context "vitis\\\\application/1584701094404"
webtalk_add_data -client vitis -key platform_source -value "platform" -context "vitis\\\\application/1584701094404"
webtalk_add_data -client vitis -key device_family -value "zynq" -context "vitis\\\\application/1584701094404"
webtalk_add_data -client vitis -key fpga -value "xc7z020" -context "vitis\\\\application/1584701094404"
webtalk_add_data -client vitis -key uid -value "1584725371885" -context "vitis\\\\application/1584725371885"
webtalk_add_data -client vitis -key project_type -value "sdk" -context "vitis\\\\application/1584725371885"
webtalk_add_data -client vitis -key os -value "standalone" -context "vitis\\\\application/1584725371885"
webtalk_add_data -client vitis -key processor -value "cortex-a9" -context "vitis\\\\application/1584725371885"
webtalk_add_data -client vitis -key runtime -value "C/C++" -context "vitis\\\\application/1584725371885"
webtalk_add_data -client vitis -key template -value "sdk" -context "vitis\\\\application/1584725371885"
webtalk_add_data -client vitis -key platform -value "custom" -context "vitis\\\\application/1584725371885"
webtalk_add_data -client vitis -key platform_type -value "fixed" -context "vitis\\\\application/1584725371885"
webtalk_add_data -client vitis -key application_type -value "application" -context "vitis\\\\application/1584725371885"
webtalk_add_data -client vitis -key platform_source -value "platform" -context "vitis\\\\application/1584725371885"
webtalk_add_data -client vitis -key device_family -value "zynq" -context "vitis\\\\application/1584725371885"
webtalk_add_data -client vitis -key fpga -value "xc7z020" -context "vitis\\\\application/1584725371885"
webtalk_transmit -clientid 36542935 -regid "" -xml E:\\Project\\Personal\\StereoVision\\Project_FPGA\\StereoDisplay\\system\\webtalk\\usage_statistics_ext_vitis.xml -html E:\\Project\\Personal\\StereoVision\\Project_FPGA\\StereoDisplay\\system\\webtalk\\usage_statistics_ext_vitis.html -wdm E:\\Project\\Personal\\StereoVision\\Project_FPGA\\StereoDisplay\\system\\webtalk\\vitis_webtalk.wdm -intro "<H3>Vitis Usage Report</H3><BR>"
webtalk_terminate
